#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE dev;
	CREATE DATABASE test;
	CREATE DATABASE prod;

	CREATE USER schema1 PASSWORD 'schema1';
	CREATE USER schema2 PASSWORD 'schema2';
	
	\c dev
	CREATE SCHEMA AUTHORIZATION schema1;
	CREATE SCHEMA AUTHORIZATION schema2;
	
	\c test
	CREATE SCHEMA AUTHORIZATION schema1;
	CREATE SCHEMA AUTHORIZATION schema2;

	\c prod
	CREATE SCHEMA AUTHORIZATION schema1;
	CREATE SCHEMA AUTHORIZATION schema2;
EOSQL