# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./schema:/docker-entrypoint-initdb.d"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080